"""Adding columns

Revision ID: dfcc88114c5b
Revises: fda2ac0268e1
Create Date: 2019-12-09 13:41:00.941382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfcc88114c5b'
down_revision = 'fda2ac0268e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('abstract', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'abstract')
    # ### end Alembic commands ###
