"""adding order to block

Revision ID: fda2ac0268e1
Revises: a1b141fcaf1b
Create Date: 2019-12-09 13:29:39.384785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fda2ac0268e1'
down_revision = 'a1b141fcaf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blocks', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blocks', 'order')
    # ### end Alembic commands ###
